apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-secret
data:
  DB_PASSWORD: ${DB_PASSWORD}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
data:
  DB_PASSWORD: ${DB_PASSWORD}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce