version: '3.8'

services:
  database:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: sh runserver.sh
    ports:
      - "8080:8080"
    env_file: .env

volumes:
  db:
