apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.postgresql.pvc.name }}
    annotaions:
        volume.beta.kubernetes.io/storage-class: local-path
        "helm.sh/resource-policy": keep
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi
    storageClassName: local-path