apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.postgresql.pvc.name }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi
    storageClassName: longhorn